In [27]:
import pandas as pd
import numpy as np

### Load phenotype and variant files

In [43]:
pheno_file_path = '/Users/christopher/Documents/Autism_Project/SSC_pheno_analysis/data/ssc_core_descriptive_tabsep.txt'
ssc_dnSNVs_path = '/Users/christopher/Documents/Autism_Project/SSC_pheno_analysis/data/DNMs.hg19.indelFilt.rptFilt.MAF001.singletons.RegDBv2.TURF.BrainSpecific.CADD.VEP.phastCons.SIFT.PolyPhen.DHS_fetal_brain_enh.DHS_fetal_brain_prom.1500bp_prom.autosomes.bed'

In [31]:
ssc_pheno_full = pd.read_csv(pheno_file_path, sep='\t')

In [32]:
ssc_pheno_full.head()

,individual,measure,abc_total_score,adi_r_b_comm_verbal_total,adi_r_comm_b_non_verbal_total,adi_r_cpea_dx,adi_r_evidence_onset,adi_r_rrb_c_total,adi_r_soc_a_total,ados_communication_social,...,srs_teacher_t_score,ssc_diagnosis_full_scale_iq,ssc_diagnosis_full_scale_iq_type,ssc_diagnosis_nonverbal_iq,ssc_diagnosis_nonverbal_iq_type,ssc_diagnosis_nvma,ssc_diagnosis_verbal_iq,ssc_diagnosis_verbal_iq_type,ssc_diagnosis_vma,vineland_ii_composite_standard_score
0,11000.p1,(11000.p1).ssc-summary-variables.1,47.0,24.0,13.0,1-autism,yes,6.0,24.0,10.0,...,NaN,65.0,2.0,78.0,1.0,79.0,50.0,2.0,55.0,74.0
1,11001.p1,(11001.p1).ssc-summary-variables.1,15.0,19.0,9.0,1-autism,yes,4.0,17.0,11.0,...,NaN,124.0,1.0,123.0,1.0,131.0,113.0,1.0,113.0,77.0
2,11002.p1,(11002.p1).ssc-summary-variables.1,14.0,21.0,12.0,1-autism,yes,8.0,27.0,14.0,...,NaN,100.0,1.0,111.0,1.0,106.0,80.0,1.0,68.0,80.0
3,11003.p1,(11003.p1).ssc-summary-variables.1,65.0,20.0,12.0,1-autism,yes,8.0,21.0,10.0,...,77.0,109.0,1.0,108.0,1.0,156.0,108.0,1.0,153.0,75.0
4,11004.p1,(11004.p1).ssc-summary-variables.1,52.0,22.0,11.0,2-asd,yes,10.0,9.0,19.0,...,NaN,59.0,1.0,74.0,1.0,117.0,31.0,1.0,72.0,64.0

### Subset wanted phenotype columns

In [33]:
wanted_columns = ['individual','sex','age_at_ados','cpea_dx','ados_css','ssc_diagnosis_verbal_iq',
                  'ssc_diagnosis_nonverbal_iq','ssc_diagnosis_full_scale_iq','adi_r_b_comm_verbal_total',
                 'adi_r_comm_b_non_verbal_total','ados_restricted_repetitive', 'adi_r_rrb_c_total',
                 'adi_r_soc_a_total','ados_social_affect','vineland_ii_composite_standard_score',
                  'rbs_r_overall_score','ados_communication_social']

In [34]:
ssc_phenos_df = ssc_pheno_full[wanted_columns].copy()
ssc_phenos_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2759 entries, 0 to 2758
Data columns (total 17 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   individual                            2759 non-null   object
 1   sex                                   2759 non-null   object
 2   age_at_ados                           2759 non-null   int64
 3   cpea_dx                               2759 non-null   object
 4   ados_css                              2758 non-null   object
 5   ssc_diagnosis_verbal_iq               2757 non-null   float64
 6   ssc_diagnosis_nonverbal_iq            2757 non-null   float64
 7   ssc_diagnosis_full_scale_iq           2753 non-null   float64
 8   adi_r_b_comm_verbal_total             2424 non-null   float64
 9   adi_r_comm_b_non_verbal_total         2757 non-null   float64
 10  ados_restricted_repetitive            2758 non-null   float64
 11  adi_r_rrb_c_total                     2757 non-null   float64
 12  adi_r_soc_a_total                     2757 non-null   float64
 13  ados_social_affect                    2758 non-null   object
 14  vineland_ii_composite_standard_score  2758 non-null   float64
 15  rbs_r_overall_score                   2756 non-null   float64
 16  ados_communication_social             2758 non-null   float64
dtypes: float64(11), int64(1), object(5)
memory usage: 366.6+ KB

In [35]:
ssc_phenos_df.head(7)

,individual,sex,age_at_ados,cpea_dx,ados_css,ssc_diagnosis_verbal_iq,ssc_diagnosis_nonverbal_iq,ssc_diagnosis_full_scale_iq,adi_r_b_comm_verbal_total,adi_r_comm_b_non_verbal_total,ados_restricted_repetitive,adi_r_rrb_c_total,adi_r_soc_a_total,ados_social_affect,vineland_ii_composite_standard_score,rbs_r_overall_score,ados_communication_social
0,11000.p1,male,110,1-autism,6,50.0,78.0,65.0,24.0,13.0,5.0,6.0,24.0,6,74.0,20.0,10.0
1,11001.p1,male,93,1-autism,7,113.0,123.0,124.0,19.0,9.0,5.0,4.0,17.0,7,77.0,3.0,11.0
2,11002.p1,female,92,1-autism,9,80.0,111.0,100.0,21.0,12.0,3.0,8.0,27.0,12,80.0,19.0,14.0
3,11003.p1,male,133,1-autism,8,108.0,108.0,109.0,20.0,12.0,5.0,8.0,21.0,9,75.0,35.0,10.0
4,11004.p1,male,190,2-asd,10,31.0,74.0,59.0,22.0,11.0,4.0,10.0,9.0,15,64.0,44.0,19.0
5,11006.p1,male,87,1-autism,9,99.0,125.0,109.0,15.0,10.0,5.0,4.0,14.0,12,89.0,13.0,14.0
6,11008.p1,male,183,1-autism,Not calculated for Module 4,133.0,119.0,129.0,17.0,10.0,2.0,4.0,23.0,Not calculated for Module 4,61.0,14.0,14.0

### Missing entries
The counts show some entries "missing" because there are some entries marked as Nan, or "not calculated"  
Ex.

In [24]:
ssc_phenos_df.loc[ssc_phenos_df['ados_css'] == 'Not calculated for Module 4'].head(2)

,individual,sex,age_at_ados,cpea_dx,ados_css,ssc_diagnosis_verbal_iq,ssc_diagnosis_nonverbal_iq,ssc_diagnosis_full_scale_iq,adi_r_b_comm_verbal_total,adi_r_comm_b_non_verbal_total,ados_restricted_repetitive,adi_r_rrb_c_total,adi_r_soc_a_total,ados_social_affect,vineland_ii_composite_standard_score,rbs_r_overall_score,ados_communication_social
6,11008.p1,male,183,1-autism,Not calculated for Module 4,133.0,119.0,129.0,17.0,10.0,2.0,4.0,23.0,Not calculated for Module 4,61.0,14.0,14.0
20,11026.p1,male,179,1-autism,Not calculated for Module 4,87.0,98.0,85.0,16.0,9.0,4.0,4.0,20.0,Not calculated for Module 4,69.0,6.0,12.0

In [25]:
ssc_phenos_df[ssc_phenos_df['vineland_ii_composite_standard_score'].isna()]

,individual,sex,age_at_ados,cpea_dx,ados_css,ssc_diagnosis_verbal_iq,ssc_diagnosis_nonverbal_iq,ssc_diagnosis_full_scale_iq,adi_r_b_comm_verbal_total,adi_r_comm_b_non_verbal_total,ados_restricted_repetitive,adi_r_rrb_c_total,adi_r_soc_a_total,ados_social_affect,vineland_ii_composite_standard_score,rbs_r_overall_score,ados_communication_social
1821,13728.p1,male,91,missing-values,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Replace "not calculated" entries with "NaN"
This way I can then convert the object types to float types and deal with all the NaNs for all columns at the same time.

"Not calculated for Module 4" is found in the ados_css and ados_social_affect columns

In [36]:
ssc_phenos_df = ssc_phenos_df.replace('Not calculated for Module 4',np.NaN)

In [37]:
ssc_phenos_df.head(7)

,individual,sex,age_at_ados,cpea_dx,ados_css,ssc_diagnosis_verbal_iq,ssc_diagnosis_nonverbal_iq,ssc_diagnosis_full_scale_iq,adi_r_b_comm_verbal_total,adi_r_comm_b_non_verbal_total,ados_restricted_repetitive,adi_r_rrb_c_total,adi_r_soc_a_total,ados_social_affect,vineland_ii_composite_standard_score,rbs_r_overall_score,ados_communication_social
0,11000.p1,male,110,1-autism,6,50.0,78.0,65.0,24.0,13.0,5.0,6.0,24.0,6,74.0,20.0,10.0
1,11001.p1,male,93,1-autism,7,113.0,123.0,124.0,19.0,9.0,5.0,4.0,17.0,7,77.0,3.0,11.0
2,11002.p1,female,92,1-autism,9,80.0,111.0,100.0,21.0,12.0,3.0,8.0,27.0,12,80.0,19.0,14.0
3,11003.p1,male,133,1-autism,8,108.0,108.0,109.0,20.0,12.0,5.0,8.0,21.0,9,75.0,35.0,10.0
4,11004.p1,male,190,2-asd,10,31.0,74.0,59.0,22.0,11.0,4.0,10.0,9.0,15,64.0,44.0,19.0
5,11006.p1,male,87,1-autism,9,99.0,125.0,109.0,15.0,10.0,5.0,4.0,14.0,12,89.0,13.0,14.0
6,11008.p1,male,183,1-autism,NaN,133.0,119.0,129.0,17.0,10.0,2.0,4.0,23.0,NaN,61.0,14.0,14.0

### Convert columns to to "float" types

In [38]:
ssc_phenos_df["ados_css"] = ssc_phenos_df['ados_css'].astype('float')
ssc_phenos_df["ados_social_affect"] = ssc_phenos_df['ados_social_affect'].astype('float')
ssc_phenos_df["age_at_ados"] = ssc_phenos_df['age_at_ados'].astype('float')

In [39]:
ssc_phenos_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2759 entries, 0 to 2758
Data columns (total 17 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   individual                            2759 non-null   object
 1   sex                                   2759 non-null   object
 2   age_at_ados                           2759 non-null   float64
 3   cpea_dx                               2759 non-null   object
 4   ados_css                              2684 non-null   float64
 5   ssc_diagnosis_verbal_iq               2757 non-null   float64
 6   ssc_diagnosis_nonverbal_iq            2757 non-null   float64
 7   ssc_diagnosis_full_scale_iq           2753 non-null   float64
 8   adi_r_b_comm_verbal_total             2424 non-null   float64
 9   adi_r_comm_b_non_verbal_total         2757 non-null   float64
 10  ados_restricted_repetitive            2758 non-null   float64
 11  adi_r_rrb_c_total                     2757 non-null   float64
 12  adi_r_soc_a_total                     2757 non-null   float64
 13  ados_social_affect                    2684 non-null   float64
 14  vineland_ii_composite_standard_score  2758 non-null   float64
 15  rbs_r_overall_score                   2756 non-null   float64
 16  ados_communication_social             2758 non-null   float64
dtypes: float64(14), object(3)
memory usage: 366.6+ KB

### Replace NaNs with the mean value for each feature

In [40]:
ssc_phenos_df.describe()

,age_at_ados,ados_css,ssc_diagnosis_verbal_iq,ssc_diagnosis_nonverbal_iq,ssc_diagnosis_full_scale_iq,adi_r_b_comm_verbal_total,adi_r_comm_b_non_verbal_total,ados_restricted_repetitive,adi_r_rrb_c_total,adi_r_soc_a_total,ados_social_affect,vineland_ii_composite_standard_score,rbs_r_overall_score,ados_communication_social
count,2759.000000,2684.000000,2757.000000,2757.000000,2753.000000,2424.000000,2757.000000,2758.000000,2757.000000,2757.00000,2684.000000,2758.000000,2756.000000,2758.000000
mean,108.316057,7.442250,78.039173,84.536815,81.170679,16.495462,9.264418,3.964104,6.519042,20.33551,11.170641,73.136693,27.130987,13.336113
std,42.801252,1.675952,31.271319,26.155693,27.959568,4.261759,3.442469,2.059634,2.494715,5.71247,4.005766,12.071746,17.391590,4.155197
min,48.000000,4.000000,5.000000,9.000000,7.000000,6.000000,0.000000,0.000000,0.000000,8.00000,2.000000,27.000000,0.000000,4.000000
25%,74.000000,6.000000,58.000000,68.000000,63.000000,13.000000,7.000000,2.000000,5.000000,16.00000,8.000000,65.000000,15.000000,10.000000
50%,100.000000,7.000000,83.000000,89.000000,85.000000,17.000000,9.000000,4.000000,6.000000,21.00000,11.000000,73.000000,24.000000,13.000000
75%,136.000000,9.000000,101.000000,103.000000,101.000000,20.000000,12.000000,5.000000,8.000000,25.00000,14.000000,81.000000,36.000000,17.000000
max,216.000000,10.000000,167.000000,161.000000,167.000000,26.000000,14.000000,8.000000,12.000000,30.00000,20.000000,115.000000,105.000000,24.000000

#### Replace NaN in a given column with its respective mean value, using a dictionary

In [41]:
means = {'ados_css': ssc_phenos_df.ados_css.mean(),
         'ssc_diagnosis_verbal_iq': ssc_phenos_df.ssc_diagnosis_verbal_iq.mean(),
         'ssc_diagnosis_nonverbal_iq': ssc_phenos_df.ssc_diagnosis_nonverbal_iq.mean(),
         'ssc_diagnosis_full_scale_iq': ssc_phenos_df.ssc_diagnosis_full_scale_iq.mean(),
        'adi_r_b_comm_verbal_total': ssc_phenos_df.adi_r_b_comm_verbal_total.mean(),
         'adi_r_comm_b_non_verbal_total': ssc_phenos_df.adi_r_comm_b_non_verbal_total.mean(),
        'ados_restricted_repetitive':ssc_phenos_df.ados_restricted_repetitive.mean(),
        'adi_r_rrb_c_total':ssc_phenos_df.adi_r_rrb_c_total.mean(),
        'adi_r_soc_a_total':ssc_phenos_df.adi_r_soc_a_total.mean(),
        'ados_social_affect':ssc_phenos_df.ados_social_affect.mean(),
        'vineland_ii_composite_standard_score':ssc_phenos_df.vineland_ii_composite_standard_score.mean(),
        'rbs_r_overall_score':ssc_phenos_df.rbs_r_overall_score.mean(),
        'ados_communication_social':ssc_phenos_df.ados_communication_social.mean()}

In [42]:
ssc_phenos_df = ssc_phenos_df.fillna(value=means)
ssc_phenos_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2759 entries, 0 to 2758
Data columns (total 17 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   individual                            2759 non-null   object
 1   sex                                   2759 non-null   object
 2   age_at_ados                           2759 non-null   float64
 3   cpea_dx                               2759 non-null   object
 4   ados_css                              2759 non-null   float64
 5   ssc_diagnosis_verbal_iq               2759 non-null   float64
 6   ssc_diagnosis_nonverbal_iq            2759 non-null   float64
 7   ssc_diagnosis_full_scale_iq           2759 non-null   float64
 8   adi_r_b_comm_verbal_total             2759 non-null   float64
 9   adi_r_comm_b_non_verbal_total         2759 non-null   float64
 10  ados_restricted_repetitive            2759 non-null   float64
 11  adi_r_rrb_c_total                     2759 non-null   float64
 12  adi_r_soc_a_total                     2759 non-null   float64
 13  ados_social_affect                    2759 non-null   float64
 14  vineland_ii_composite_standard_score  2759 non-null   float64
 15  rbs_r_overall_score                   2759 non-null   float64
 16  ados_communication_social             2759 non-null   float64
dtypes: float64(14), object(3)
memory usage: 366.6+ KB

### Format variant file

In [46]:
ssc_dnsnvs_full = pd.read_csv(ssc_dnSNVs_path, sep='\t')

In [47]:
ssc_dnsnvs_full.head()

,chrom,start,end,ref,alt,famID,child,regDB2.0,SURF,TURF,raw_CADD,CADD,VEP,phastCons,SIFT,PolyPhen,fetal_brain_enh_dhs,fetal_brain_prom_dhs,promoter_1500bp
0,chr1,17483,17484,G,A,13850,proband,5,0.42,0.110964,-0.244724,0.530,intron_variant,.,.,.,.,.,.
1,chr1,84096,84097,T,A,13123,sibling,5,0.70,0.224910,0.032822,3.143,intergenic_variant,.,.,.,.,.,.
2,chr1,85826,85827,T,C,13727,sibling,7,0.00,0.000000,-0.084777,1.549,downstream_gene_variant,.,.,.,.,.,.
3,chr1,238324,238325,G,A,12299,sibling,6,0.19,0.056164,-0.541013,0.065,intron_variant,.,.,.,.,.,.
4,chr1,525764,525765,G,A,13047,sibling,7,0.00,0.000000,0.026286,3.037,intron_variant,.,.,.,.,.,.